4fitClub/4fitClub/Models/Imagens.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace _4fitClub.Models
{
    public class Imagens
    {

        public int ID { get; set; }

        public string Nome { get; set; }

        public int Ordem { get; set; } //ordem de apresentação

        public string Tipo { get; set; } // se é imagem ou vídeo


        //FK para a tabela dos Exercicios
        [ForeignKey("Exercicio")]
        public int ExercicioFK { get; set; }
        public virtual Exercicios Exercicio { get; set; }

    }
}

4fitClub/4fitClub/Controllers/ImagensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _4fitClub.Models;

namespace _4fitClub.Controllers
{
    [Authorize(Roles = "Manager")]
    public class ImagensController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        /// <summary>
        /// Ação que entrega para a vista as imagens ordenadas por 
        /// </summary>
        /// <returns></returns>
        // GET: Imagens
        public ActionResult Index()
        {
            //Ordena as imagens por Tipo de exercicio
            var listaDeImagens = db.Imagens.ToList().OrderBy(i => i.ExercicioFK);
            return View(listaDeImagens);
        }
        /// <summary>
        /// detalhes das imagens
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Imagens/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index/Index");
            }
            Imagens imagens = db.Imagens.Find(id);
            if (imagens == null)
            {
                return RedirectToAction("Index/Index");
            }
            return View(imagens);
        }

        // GET: Imagens/Create
        public ActionResult Create()
        {
            ViewBag.ExercicioFK = new SelectList(db.Exercicios, "ID", "Nome");
            return View();
        }
        /// <summary>
        /// Adicionar uma nova imagem de um exercícios
        /// </summary>
        /// <param name="imagens"></param>
        /// <param name="uploadFotografia"></param>
        /// <returns></returns>
        // POST: Imagens/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Ordem,Tipo,ExercicioFK")] Imagens imagens, HttpPostedFileBase uploadFotografia)
        {
            int id = 0;

            try
            {
                // o id será mais 1 que o último
                id = db.Imagens.Max(i => i.ID) + 1;
            }
            catch(Exception)
            {
                id = 1;
            }

            imagens.ID = id;
            //atribuição do nome da imagem para ser guardada na base de dados
            string nomeImagem = "Img_" + id + ".jpg";
            //var auxiliar
            string path = "";

            if(uploadFotografia != null)
            {
                    //caminho para a imagem
                    path = Path.Combine(Server.MapPath("~/multimedia/"), nomeImagem);
             
                //novo nome da imagem
                imagens.Nome = nomeImagem;


            }
            else
            {
                ModelState.AddModelError("", "Não foi fornecida uma imagem");
                return View(imagens);
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //adiciona a base de dados os novos dados
                    db.Imagens.Add(imagens);
                    //commit na base de dados
                    db.SaveChanges();
                    //guarda a fotografia na base de dados no caminho feito anteriormente
                    uploadFotografia.SaveAs(path);
                    //redireciona para a View das imagens
                    return RedirectToAction("Index/Index");
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Houve um erro na adição da imagem...");
                }
            }

            ViewBag.ExercicioFK = new SelectList(db.Exercicios, "ID", "Nome", imagens.ExercicioFK);
            return View(imagens);
        }

        // GET: Imagens/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index/Index");
            }
            Imagens imagens = db.Imagens.Find(id);
            if (imagens == null)
            {
                return RedirectToAction("Index/Index");
            }
            ViewBag.ExercicioFK = new SelectList(db.Exercicios, "ID", "Nome", imagens.ExercicioFK);
            return View(imagens);
        }
        /// <summary>
        /// Edição da imagens de um exercício
        /// </summary>
        /// <param name="imagens"></param>
        /// <param name="uploadImagem"></param>
        /// <returns></returns>
        // POST: Imagens/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nome,Ordem,Tipo,ExercicioFK")] Imagens imagens, HttpPostedFileBase uploadImagem)
        {
            string nomeImagem = "Img_" + imagens.ID + ".jpg";

            string path = "";

            if (uploadImagem!=null)
            {
                if (uploadImagem.FileName.EndsWith("jpg") || uploadImagem.FileName.EndsWith("png"))
                {
                    path = Path.Combine(Server.MapPath("~/multimedia/"), nomeImagem);
                }
                else
                {
                    ModelState.AddModelError("", "Ficheiro não é uma imagem");
                }
                imagens.Nome = nomeImagem;
            }
            if (ModelState.IsValid)
            {
                db.Entry(imagens).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.ExercicioFK = new SelectList(db.Exercicios, "ID", "Nome", imagens.ExercicioFK);

                if (uploadImagem != null)
                {
                    uploadImagem.SaveAs(path);

                }
                return RedirectToAction("Index/Index");
            }
            return View(imagens);
        }

        // GET: Imagens/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index/Index");
            }
            Imagens imagens = db.Imagens.Find(id);
            if (imagens == null)
            {
                return RedirectToAction("Index/Index");
            }
            return View(imagens);
        }
        /// <summary>
        /// Ação que irá apagar a imagem
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // POST: Imagens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Imagens imagens = db.Imagens.Find(id);
            try
            {
                db.Imagens.Remove(imagens);
                db.SaveChanges();
                return RedirectToAction("Index/Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", string.Format("Não é possível apagar a Imagem {0}, existem elementos associados à imagem",
                                           imagens.Nome)
               );
            }
            return View(imagens);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

4fitClub/4fitClub/Views/Imagens/Create.cshtml
@model _4fitClub.Models.Imagens



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm("Create","Imagens",FormMethod.Post, new { enctype="multipart/form-data"}))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h3>Multimédia</h3>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.Label("Imagem", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*tml.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })*@
                    @*Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })*@
                    <input type="file" name="uploadFotografia"
                           style="color:blue;" accept="image/*" />
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Ordem, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Ordem, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ordem, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Tipo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ExercicioFK, "Exercício", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ExercicioFK", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ExercicioFK, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Adicionar" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("voltar atrás", "Index/Index")
    </div>
</body>
</html>

4fitClub/4fitClub/Views/Imagens/Delete.cshtml
@model _4fitClub.Models.Imagens



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Tem a certeza que quer eliminar multimédia?</h3>
    <div>
        @* HTML Helper para apresentar as mensagens de erro *@
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayName("Exercício")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Exercicio.Nome)
            </dd>

            <dt>
                @Html.DisplayName("Imagem")
            </dt>

            <dd>
                @*Html.DisplayFor(model => model.Nome)*@
                <a href="~/multimedia/@Model.Nome" target="_blank">
                    <img src="~/multimedia/@Model.Nome" width="200" />
                </a>
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Ordem)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Ordem)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Tipo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Tipo)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Eliminar Multimédia" class="btn btn-danger" /> |
                @Html.ActionLink("Voltar atrás", "Index/Index")
            </div>
        }
    </div>
</body>
</html>

4fitClub/4fitClub/Views/Imagens/Details.cshtml
@model _4fitClub.Models.Imagens



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h3>Multimédia</h3>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayName("Exercício")
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Exercicio.Nome)
            </dd>
    
            <dt>
                @Html.DisplayName("Imagem")
            </dt>
    
            <dd>
                @*Html.DisplayFor(model => model.Nome)*@
                <a href="~/multimedia/@Model.Nome" target="_blank">
                    <img src="~/multimedia/@Model.Nome" width="200"  />
                </a>
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Ordem)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Ordem)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Tipo)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Tipo)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Editar detalhes", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Voltar atrás", "Index/Index")
    </p>
</body>
</html>

4fitClub/4fitClub/Views/Imagens/Edit.cshtml
@model _4fitClub.Models.Imagens


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm("Edit","Imagens", FormMethod.Post, new { enctype = "multipart/form-data"} ))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h3>Multimédia</h3>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)
            @Html.HiddenFor(model => model.Nome)
    
            <div class="form-group">
                @Html.Label("Imagem", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })*@
                    <a href="~/multimedia/@Model.Nome" target="_blank">
                        <img src="~/multimedia/@Model.Nome" height="150"/>

                    </a>
                    
                    <input type="file" name="uploadImagem"
                           style="color:blue;" accept="image/*" />
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Ordem, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Ordem, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ordem, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Tipo, "Tipo (Imagem ou Vídeo)",htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Tipo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ExercicioFK, "Exercício", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ExercicioFK", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ExercicioFK, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Guardar Alterações" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Voltar atrás", "Index/Index")
    </div>
</body>
</html>

4fitClub/4fitClub/Views/Imagens/Index.cshtml
@model IEnumerable<_4fitClub.Models.Imagens>



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h3>Multimédia</h3>
    <p>
        @Html.ActionLink("Adicionar Multimédia", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Exercício")
                @*Html.DisplayNameFor(model => model.Exercicio.Nome)*@
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ordem)
            </th>
            <th>
                @Html.DisplayName("Tipo de multimédia")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Exercicio.Nome)
                </td>
                <td>
                    @*Html.DisplayFor(modelItem => item.Nome)*@
                    <a href="~/multimedia/@item.Nome" target="_blank">
                        <img src="~/multimedia/@item.Nome" width="190" />
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ordem)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tipo)
                </td>
                <td>
                    @Html.ActionLink("Editar detalhes Multimédia", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Detalhes Multimédia", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Eliminar Multimédia", "Delete", new { id = item.ID })
                </td>
            </tr>
        }

    </table>
</body>
</html>