4fitClub/4fitClub/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _4fitClub.Models
{
    public class Cliente
    {
        public Cliente()
        {
            ListaDePlanos = new HashSet<Planos>();
        }


        public int ID { get; set; }

        public string Nome { get; set; }
    
        public string Imagem { get; set; }

        public string UserName { get; set; }

        // Lista de Planos do cliente
        public virtual ICollection<Planos> ListaDePlanos { get; set; }

    }
}

4fitClub/4fitClub/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _4fitClub.Models;

namespace _4fitClub.Controllers
{
    [Authorize(Roles = "Manager,Utilizador")]
    public class ClientesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        /// <summary>
        /// Ação para visualização dos clientes na aplicação
        /// </summary>
        /// <returns></returns>
        // GET: Clientes
        [Authorize(Roles = "Manager")]
        public ActionResult Index()
        {
            return View(db.Cliente.ToList());
        }

        // GET: Clientes/Details/5
        [Authorize(Roles = "Manager")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return RedirectToAction("Index");
            }


            return View(cliente);
        }

        // GET: Clientes/Create
        [Authorize(Roles = "Manager")]
        public ActionResult Create()
        {
            return View();
        }
        /// <summary>
        /// Ação para criação de cliente, mas não átiva
        /// Isto deve-se ao facto dos clientes criarem as sua própias contas 
        /// e automáticamente é adicionado à base de dados por isso esta funcionalidade 
        /// do lado do "Manager" não está átiva
        /// </summary>
        /// <param name="cliente"></param>
        /// <returns></returns>
        // POST: Clientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nome,Imagem,UserName")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Cliente.Add(cliente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cliente);
        }

        // GET: Clientes/Edit/5
        [Authorize(Roles = "Manager,Utilizador")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                if (User.IsInRole("Utilizador"))
                {
                    return RedirectToAction("Index", "Manage");
                }
                return RedirectToAction("Index");
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                if (User.IsInRole("Utilizador"))
                {
                    return RedirectToAction("Index", "Manage");
                }
                return RedirectToAction("Index");
            }
            if (User.IsInRole("Manager") || User.Identity.Name.Equals(cliente.UserName))
            {
                return View(cliente);
            }
            if (User.IsInRole("Utilizador"))
            {
                return RedirectToAction("Index", "Manage");
            }
            return RedirectToAction("Index");
        }
        /// <summary>
        /// Ação para Edição que recebe a imagem do upload e o Cliente
        /// </summary>
        /// <param name="cliente"></param>
        /// <param name="uploadImagemEdit"></param>
        /// <returns></returns>
        // POST: Clientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nome,Imagem,UserName")] Cliente cliente, HttpPostedFileBase uploadImagemEdit)
        {
            string novaImagem = "User_" + cliente.ID + ".jpg";

            string path = "";

            if (uploadImagemEdit != null)
            {
                if (uploadImagemEdit.FileName.EndsWith("jpg") || uploadImagemEdit.FileName.EndsWith("png"))
                {
                    path = Path.Combine(Server.MapPath("~/UserImages"), novaImagem);

                }
                else
                {
                    ModelState.AddModelError("", "Ficheiro não é uma imagem");
                }
                cliente.Imagem = novaImagem;
            }

            if (ModelState.IsValid)
            {
                db.Entry(cliente).State = EntityState.Modified;
                db.SaveChanges();
                if (uploadImagemEdit != null)
                {
                    uploadImagemEdit.SaveAs(path);
                }
                if (User.IsInRole("Utilizador"))
                {
                    return RedirectToAction("Index", "Manage");
                }
                else
                {
                    return RedirectToAction("Index");
                }
               
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        [Authorize(Roles = "Manager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return RedirectToAction("Index");
            }
            return View(cliente);
        }
        /// <summary>
        /// Tal como o create, para apagar o cliente seria uma decisão interna
        /// Na minha opinião pode ser feita mas isto gera o problema de haver planos criados
        /// que não têm nenhum cliente associado o impossibilita a eliminação desses planos
        /// Por isso decidi não fazer a eliminação do cliente. Mas mais uma vez
        /// na minha opinão deve ser possível a sua eliminação
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cliente cliente = db.Cliente.Find(id);
            
            try
            {
                db.Cliente.Remove(cliente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", string.Format("Não é possível apagar o Cliente {0}, existem planos de treino associados ao Cliente",
                                            cliente.Nome)
                );
            }
            return View(cliente);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

4fitClub/4fitClub/Views/Clientes/Create.cshtml
@model _4fitClub.Models.Cliente



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h3>Clientes da Aplicação</h3>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Imagem, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Imagem, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Imagem, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Voltar atrás", "Index")
    </div>
</body>
</html>

4fitClub/4fitClub/Views/Clientes/Delete.cshtml
@model _4fitClub.Models.Cliente



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Tem a certeza que quer eliminar este Cliente?</h3>
    <div>
        @* HTML Helper para apresentar as mensagens de erro *@
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nome)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nome)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Imagem)
            </dt>

            <dd>
                <a href="~/UserImages/@Model.Imagem" target="_blank">
                    <img src="~/UserImages/@Model.Imagem" width="200" />
                </a>
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UserName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserName)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                @Html.ActionLink("voltar atrás", "Index")
            </div>
        }
    </div>
</body>
</html>

4fitClub/4fitClub/Views/Clientes/Details.cshtml
@model _4fitClub.Models.Cliente


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Detalhes do Cliente</title>
</head>
<body>
    <div>
        <h3>Cliente</h3>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nome)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nome)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Imagem)
            </dt>

            <dd>
                <a href="~/UserImages/@Model.Imagem" target="_blank">
                    <img src="~/UserImages/@Model.Imagem" width="200" />
                </a>
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UserName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserName)
            </dd>
        </dl>
        <div class="form-group">
            <b>@Html.DisplayName("Os meus planos:")</b>
            <ul>
                @foreach (var item in Model.ListaDePlanos.OrderBy(p => p.Nome))
                {
                    <li>@Html.DisplayFor(model => item.Nome)</li>
                }
            </ul>
        </div>
    </div>
    <p>
        @Html.ActionLink("Editar Cliente", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Voltar atrás", "Index")
    </p>
</body>
</html>

4fitClub/4fitClub/Views/Clientes/Edit.cshtml
@model _4fitClub.Models.Cliente



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm("Edit", "Clientes", FormMethod.Post,new { enctype = "multipart/form-data"}))
    {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <h3>Cliente</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.UserName)
        @Html.HiddenFor(model => model.Imagem)
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <a href="~/UserImages/@Model.Imagem" target="_blank">
                    <img src="~/UserImages/@Model.Imagem" width="200" />
                </a>
                <input type="file" name="uploadImagemEdit"
                       style="color:blue;" accept="image/*" />
                @Html.ValidationMessageFor(model => model.Imagem, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
    }
    
        <div>
            @if (User.IsInRole("Utilizador"))
            {
                @Html.ActionLink("Voltar ao Perfil", "Index", "Manage", null, null)
            }
            @if (User.IsInRole("Manager")){
                @Html.ActionLink("Voltar ao Perfil", "Index")
            }


        </div>
</body>
</html>

4fitClub/4fitClub/Views/Clientes/Index.cshtml
@model IEnumerable<_4fitClub.Models.Cliente>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h3>Clientes da Aplicação</h3>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    <a href="~/UserImages/@item.Imagem" target="_blank">
                        <img src="~/UserImages/@item.Imagem" width="100" />
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.ActionLink("Editar Perfil de Cliente", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Detalhes do cliente", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Eliminar Cliente", "Delete", new { id = item.ID })
                </td>
            </tr>
        }

    </table>
</body>
</html>