4fitClub/4fitClub/Models/Planos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace _4fitClub.Models
{

    public class Planos
    {
        public Planos()
        {
            ListaDeExercicios = new HashSet<Exercicios>();
        }

        [Key]
        public int ID { get; set; } //Primary key

        public string Nome { get; set; }

        public string Descricao { get; set; }

        public DateTime DataCriacao { get; set; }

        //incluir data de inicio de criação
        //public DateTime DataCriacao { get; set; }
        //*************************************************************
        // chave estrangeira para o cliente que possui um conjunto de planos
        [ForeignKey("Cliente")]
        public int ClienteFK { get; set; }
        public virtual Cliente  Cliente { get; set; }


        // relacionamento muito para muitos com os exercicios
        public virtual ICollection<Exercicios> ListaDeExercicios { get; set; }
        //associar a uma lista de utilizadores. Cada utilizador vai ter acesso
        //aos seus planos


    }
}

4fitClub/4fitClub/Controllers/ExerciciosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _4fitClub.Models;

namespace _4fitClub.Controllers
{
    [Authorize(Roles = "Manager,Utilizador")]
    public class ExerciciosController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();
        /// <summary>
        /// Visualização dos exercícios ordenados pelo nome
        /// </summary>
        /// <returns></returns>
        // GET: Exercicios
        [AllowAnonymous]
        public ActionResult Index()
        {
            var exercicios = db.Exercicios.Include(e => e.Categoria).ToList().OrderBy(e => e.Nome);
            return View(exercicios);
        }

        // GET: Exercicios/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Exercicios exercicios = db.Exercicios.Find(id);
            if (exercicios == null)
            {
                return RedirectToAction("Index");
            }
            return View(exercicios);
        }

        // GET: Exercicios/Create
        [Authorize(Roles = "Manager")]
        public ActionResult Create()
        {
            ViewBag.CategoriaFK = new SelectList(db.Categorias, "ID", "Nome");
            return View();
        }
        /// <summary>
        /// Ação para criar um exercício
        /// </summary>
        /// <param name="exercicios"></param>
        /// <returns></returns>
        // POST: Exercicios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nome,Objetivo,Passos,CategoriaFK")] Exercicios exercicios)
        {
            if (ModelState.IsValid)
            {
                db.Exercicios.Add(exercicios);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoriaFK = new SelectList(db.Categorias, "ID", "Nome", exercicios.CategoriaFK);
            return View(exercicios);
        }
        
        // GET: Exercicios/Edit/5
        [Authorize(Roles = "Manager")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Exercicios exercicios = db.Exercicios.Find(id);
            if (exercicios == null)
            {
                return RedirectToAction("Index");
            }
            ViewBag.CategoriaFK = new SelectList(db.Categorias, "ID", "Nome", exercicios.CategoriaFK);
            return View(exercicios);
        }
        /// <summary>
        /// Ação para edição do exercício
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // POST: Exercicios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nome,Objetivo,Passos,CategoriaFK")] Exercicios exercicios)
        {
            if (ModelState.IsValid)
            {
                db.Entry(exercicios).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoriaFK = new SelectList(db.Categorias, "ID", "Nome", exercicios.CategoriaFK);
            return View(exercicios);
        }

        // GET: Exercicios/Delete/5
        [Authorize(Roles = "Manager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Exercicios exercicios = db.Exercicios.Find(id);
            if (exercicios == null)
            {
                return RedirectToAction("Index");
            }
            return View(exercicios);
        }
        /// <summary>
        /// Ação para eliminação do exercício
        /// Não vai ser possível caso haja elementos associados no caso planos e imagens
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // POST: Exercicios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
  
        public ActionResult DeleteConfirmed(int id)
        {
            Exercicios exercicios = db.Exercicios.Find(id);
            try
            {
                db.Exercicios.Remove(exercicios);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {

                ModelState.AddModelError("", string.Format("Não é possível apagar o exercício {0}, existem elementos associados ao exercício",
                                          exercicios.Nome)
              );
            }
            return View(exercicios);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

4fitClub/4fitClub/Controllers/PlanosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _4fitClub.Models;

namespace _4fitClub.Controllers
{
    [Authorize(Roles = "Utilizador")]
    public class PlanosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        /// <summary>
        /// Retorna os planos de um utilizador ordenados pela data de criação 
        /// </summary>
        /// <returns></returns>
        // GET: Planos
        public ActionResult Index()
        {
            ///retorna os planos do user que efetuou login
            var planos = db.Planos
                            .Where(p => p.Cliente.UserName.Equals(User.Identity.Name))
                            .Include(p => p.Cliente);
            
               
                
            return View(planos.ToList().OrderByDescending(p => p.DataCriacao));
        }
        /// <summary>
        /// Detalhes de um plano, e na view será possível visualizar os exercícios do plano,
        /// com link para o exercício
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Planos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Planos planos = db.Planos.Find(id);
            if (planos == null)
            {
                return RedirectToAction("Index");
            }

            return View(planos);
        }

        // GET: Planos/Create
        public ActionResult Create()
        {
            ViewBag.ListaExercicios = db.Exercicios.OrderBy(e => e.Nome).ToList();
            return View();
        }
        /// <summary>
        /// Cria um plano, em que podem ser incluídos os exercícios
        /// </summary>
        /// <param name="planos"></param>
        /// <param name="opcoesEscolhidas"></param>
        /// <returns></returns>
        // POST: Planos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nome,Descricao")] Planos planos, string[] opcoesEscolhidas)
        {
            //falta relaciona tablea de login para preencher os dados do cliente


            //retornar o id do cliente autenticado
            //var cliente = db.Cliente.Find(planos.ClienteFK).ID;
            var cliente = db.Cliente.Where(p => p.UserName.Equals(User.Identity.Name)).Single().ID;

            planos.ClienteFK = cliente;
            planos.DataCriacao = DateTime.Now;
            var exercicios = db.Exercicios.ToList();

            foreach (var ee in exercicios)
            {
                if (opcoesEscolhidas.Contains(ee.ID.ToString()))
                {
                    if (!planos.ListaDeExercicios.Contains(ee))
                    {
                    planos.ListaDeExercicios.Add(ee);
                    }
                }
                else
                {
                    planos.ListaDeExercicios.Remove(ee);
                }
            }

            if (ModelState.IsValid)
            {
                db.Planos.Add(planos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(planos);
        }

        // GET: Planos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Planos planos = db.Planos.Find(id);
            if (planos == null)
            {
                return RedirectToAction("Index");
            }

            // gerar a lista de objetos de exercicios que podem ser associados aos planos
            ViewBag.ListaExercicios = db.Exercicios.OrderBy(e => e.Nome).ToList();
            return View(planos);
        }
        /// <summary>
        /// Edição do plano, pode-se adiciona ou retirar exercícios
        /// </summary>
        /// <param name="planos"></param>
        /// <param name="opcoesEscolhidas"></param>
        /// <returns></returns>
        // POST: Planos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nome,Descricao")] Planos planos, string[] opcoesEscolhidas)
        {
            // ler da BD o objeto que se pretende editar
            var pp = db.Planos.Include(e => e.ListaDeExercicios).Where(e => e.ID == planos.ID).SingleOrDefault();

            if (ModelState.IsValid)
            {
                pp.Nome = planos.Nome;
                pp.Descricao = planos.Descricao;
            }
            else
            {
                // gerar a lista de objetos de exercicios que podem ser associados aos planos
                ViewBag.ListaExercicios = db.Exercicios.OrderBy(e => e.Nome).ToList();
                // devolver o controlo à View
                return View(planos);
            }

            // tentar fazer o Update
            if (TryUpdateModel(pp, "", new string[] { nameof(pp.Nome), nameof(pp.Descricao), nameof(pp.ListaDeExercicios) }))
            {
                //obter lista de exercicios
                var exercicios = db.Exercicios.ToList();

                if (opcoesEscolhidas != null)
                {
                    // se existirem opções escolhidas, vamos associá-las
                    foreach (var ee in exercicios)
                    {
                        if (opcoesEscolhidas.Contains(ee.ID.ToString()))
                        {
                            // se uma opção escolhida ainda não está associada, cria-se a associação
                            if (!pp.ListaDeExercicios.Contains(ee))
                            {
                                pp.ListaDeExercicios.Add(ee);
                            }
                        }
                        else
                        {
                            // caso exista associação para uma opção que não foi escolhida, 
                            // remove-se essa associação
                            pp.ListaDeExercicios.Remove(ee);
                        }
                    }
                }
                else
                {
                    // não existem opções escolhidas!
                    // vamos eliminar todas as associações
                    foreach (var ee in exercicios)
                    {
                        if (pp.ListaDeExercicios.Contains(ee))
                        {
                            pp.ListaDeExercicios.Remove(ee);
                        }
                    }
                }
                //guardar alterações
                db.SaveChanges();

                //devolver controlo à View
                return RedirectToAction("Index");
            }

            // se cheguei aqui, é pq alguma coisa correu mal
            ModelState.AddModelError("", "Alguma coisa correu mal...");

            // gerar a lista de objetos de exercicios que podem ser associados aos planos
            ViewBag.ListaExercicios = db.Exercicios.OrderBy(e => e.Nome).ToList();


            // visualizar View...
            return View(planos);
        }

        // GET: Planos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Planos planos = db.Planos.Find(id);
            if (planos == null)
            {
                return RedirectToAction("Index");
            }
            return View(planos);
        }
        /// <summary>
        /// O cliente pode apagar o plano, tirando a associação aos exercícios,
        /// podendo remover com segurança o plano
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // POST: Planos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Planos planos = db.Planos.Find(id);
            // ler da BD o objeto que se pretende eliminar
            var pp = db.Planos.Include(e => e.ListaDeExercicios).Where(e => e.ID == planos.ID).SingleOrDefault();
            //obter lista de exercicios
            var exercicios = db.Exercicios.ToList();
            foreach (var ee in exercicios)
            {
                if (pp.ListaDeExercicios.Contains(ee))
                {
                    pp.ListaDeExercicios.Remove(ee);
                }
            }
            db.Planos.Remove(planos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

4fitClub/4fitClub/Views/Planos/Create.cshtml
@model _4fitClub.Models.Planos



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <h4>Planos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2">Adiciona Exercícios</span>
            <div class="col-md-10">
                @{ string selected = "";}
                @foreach (var item in ViewBag.ListaExercicios)
                {
  
                    <input type="checkbox" name="opcoesEscolhidas" value="@item.ID" @selected /> @item.Nome
                    <br />
                }
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
    }
    
    <div>
        @Html.ActionLink("Voltar aos meus Planos", "Index")
    </div>
</body>
</html>

4fitClub/4fitClub/Views/Planos/Delete.cshtml
@model _4fitClub.Models.Planos



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Tem a certeza que quer eliminar ?</h3>
    <div>
        <h4>Planos</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nome)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nome)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Descricao)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Descricao)
            </dd>

            <dt>
                @Html.DisplayName("Data de Criação do Plano")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DataCriacao)
            </dd>

        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Apagar" class="btn btn-danger" /> |
                @Html.ActionLink("Voltar atrás", "Index")
            </div>
        }
    </div>
</body>
</html>

4fitClub/4fitClub/Views/Planos/Details.cshtml
@model _4fitClub.Models.Planos



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Planos</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nome)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nome)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Descricao)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Descricao)
            </dd>

            <dt>
                @Html.DisplayName("Data de Criação do Plano")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DataCriacao)
            </dd>
        </dl>
        <div class="form-group">
            <b>@Html.DisplayName("Exercícios do meu plano:")</b>
            <ul>
                @foreach (var item in Model.ListaDeExercicios.OrderBy(e => e.Nome))
                {
                <li>@Html.ActionLink(item.Nome, "Details", "Exercicios", new { id = item.ID }, new { target="_blank"})</li>
                }
            </ul>
        </div>


    </div>
    <p>
        @Html.ActionLink("Alterar Plano", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("voltar atrás", "Index")
    </p>
</body>
</html>

4fitClub/4fitClub/Views/Planos/Edit.cshtml
@model _4fitClub.Models.Planos



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Planos</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <span class="control-label col-md-2">Exercícios do meu plano</span>
                <div class="col-md-10">
                    @{ string selected = "";}
                    @foreach (var item in ViewBag.ListaExercicios)
                    {
                        selected = "";
                        foreach (int opcaoID in Model.ListaDeExercicios.Select(e => e.ID))
                        {
                            if (item.ID == opcaoID)
                            {
                                selected = "checked";
                            }
                        }
                        <input type="checkbox" name="opcoesEscolhidas" value="@item.ID" @selected /> @item.Nome
                        <br />
                    }
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Guardar Alterações" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Voltar atrás", "Index")
    </div>
</body>
</html>

4fitClub/4fitClub/Views/Planos/Index.cshtml
@model IEnumerable<_4fitClub.Models.Planos>



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h3>Meus Planos de Treino</h3>
    <p>
        @Html.ActionLink("Criar Novo Plano de Treino", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayName("Data de Criação do Plano")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataCriacao)
            </td>
            <td>
                @Html.ActionLink("Editar Plano de Treino", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Detalhes do Plano de Treino", "Details", new { id = item.ID }) |
                @Html.ActionLink("Eliminar Plano de Treino", "Delete", new { id = item.ID })
            </td>
        </tr>
        }

    </table>
</body>
</html>